name: Lint
on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  lint:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v3
        with:
          python-version: "3.10"
          architecture: x64
      - run: pip install --upgrade virtualenv pip setuptools
      - run: virtualenv .venv
      - run: source .venv/bin/activate; pip install flit==3.8.0
      - run: make install
      - run: make lint